### ISSUE TITLE
Additional fields

### ISSUE THREAD

**Issue by pykong** [juancarlospaco/peewee-extra-fields#8]
If those fields are not implemented, yet.
They should as they are commonly used:

- URL
- Arrow
- Maya

**Comment by pykong** [comment]
Anyone is free to post new suggestions.

**Comment by ghost** [comment]
URL can be pretty much anything, but I think is better to have specific URL like for HTTP, Bitcoin, Bittorrent, etc.

Whats Arrow and Maya?, the time libs?, they should use the Pickled field, or use ISO format standard.
[When 3.7 is released some Time stuff will have to change because of Nanoseconds.](https://www.python.org/dev/peps/pep-0564/)
I say we wait and see after the 3.7 final is released.

**Comment by pykong** [comment]
Still, we could have an URL field validating against a general regex pattern fitting all URLs.

Arrow and Maya are popular alternatives to DateTime.
I like to use the former over standard DateTime modules.
They come with a more friendly API.

I am testing an Arrow based field right now.
Any changes should be unaffected by `PEP564`. but we could keep PR open and wait til release of 3.7 stable.

This issue is about collecting some ideas/wishes for new fields.
Some inspiration: https://sqlalchemy-utils.readthedocs.io/en/latest/data_types.html
(Guess most are already implemented here.)

**Comment by ghost** [comment]
`peewee_extra_fields` now has `MoneyField` and `XMLField` using Postgres database native types for maximum performance, Docs on Readme, Tests on Travis CI using an actual Postgres database.
